matrix:
  COMPONENT:
    - weave
    - weaveexec
    - weaveplugin
  VERSION:
    - "master"
    - "1.4.3"

build:
  image: armhfbuild/docker:1.9.1-dind
  privileged: true
  commands:
    - cd $$VERSION
    - ./build.sh
  when:
    VERSION: master

build:
  image: armhfbuild/golang:1.5.3
  commands:
    - cd $$VERSION
    - VERSION=$$VERSION ./build.sh
  when:
    VERSION: "1.4.3"

publish:
  docker:
    file: "$$VERSION/weave/prog/weaver/Dockerfile"
    context: "$$VERSION/weave/prog/weaver"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/weave
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
    when:
      COMPONENT: weave

  docker:
    file: "$$VERSION/weave/prog/weaveexec/Dockerfile"
    context: "$$VERSION/weave/prog/weaveexec"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/weaveexec
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
    when:
      COMPONENT: weaveexec

  docker:
    file: "$$VERSION/weave/prog/plugin/Dockerfile"
    context: "$$VERSION/weave/prog/plugin"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/weaveplugin
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
    when:
      COMPONENT: weaveplugin
