matrix:
  VERSION:
    - "master"
    # - "1.4.3"

build:
  image: armhfbuild/docker:1.9.1-dind
  privileged: true
  commands:
    - cd $$VERSION
    - ./build.sh

publish:
  docker:
    file: "$$VERSION/prog/weaver/Dockerfile"
    context: "$$VERSION/prog/weaver"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/weave
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

  docker:
    file: "$$VERSION/prog/weaveexec/Dockerfile"
    context: "$$VERSION/prog/weaveexec"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/weaveexec
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

  docker:
    file: "$$VERSION/prog/plugin/Dockerfile"
    context: "$$VERSION/prog/plugin"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/weaveplugin
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
